### ISSUE TITLE
Нет сохранения IP

### ISSUE THREAD

**Issue by XEGARE** [Geebrox/GRP#1]
Здравствуйте! Не сохраняется IP при регистрации. Скорее всего вы забыли GetPlayerIP

**Comment by ismoiliy98** [comment]
Будет исправлен!

**Comment by XEGARE** [comment]
Так же есть второй баг. В БД то прописывается по умолчанию 100, но в игре выдается всего 10 ХП.

**Comment by ismoiliy98** [comment]
Указанные баги исправлены. Исправление будут предоставлены в новой версии проекта.
